@testBaseUrl = TODO
@prodBaseUrl = https://fqgu8rbpjk.execute-api.eu-central-1.amazonaws.com
@baseUrl = {{prodBaseUrl}}





#####################################
### Create a donation ###
#####################################
@emailOne = "john@icloud.com"
@emailTwo = "mary@icloud.com"
@invalidEmail = "invalidEmail"
POST {{baseUrl}}/donations HTTP/1.1
Content-Type: application/json

{
      "email": {{emailTwo}},
      "amount": 10
}





#####################################
### Get Donation by transactionId ###
#####################################
@transactionId = 1d916d54-ccb1-4fe5-8673-6fc169ddfa3c
GET {{baseUrl}}/donations/{{transactionId}} HTTP/1.1





#####################################
### Get User by email ###
#####################################
@maryEmail = mary@icloud.com
@johnEmail = john@icloud.com
GET {{baseUrl}}/user/{{johnEmail}} HTTP/1.1





#####################################
### Get all donations by user ###
#####################################
GET {{baseUrl}}/user/donations/{{maryEmail}} HTTP/1.1